# Generated by Django 3.0.7 on 2020-06-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200613_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='price',
            field=models.FloatField(default=199.99),
        ),
    ]
