# Generated by Django 3.0.7 on 2020-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipmentmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='price',
            field=models.IntegerField(default=199),
        ),
    ]
