# Generated by Django 3.0.7 on 2020-07-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutusmodel_cateringmodel_eventsmodel_imagesmodel_registermodel_standmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='cateringmodel',
            options={'verbose_name': 'Кейтеринг', 'verbose_name_plural': 'Кейтеринг'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудования'},
        ),
        migrations.AlterModelOptions(
            name='eventsmodel',
            options={'verbose_name': 'Ивенты', 'verbose_name_plural': 'Ивенты'},
        ),
        migrations.AlterModelOptions(
            name='imagesmodel',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='registermodel',
            options={'verbose_name': 'Регистрация посетителей', 'verbose_name_plural': 'Регистрация посетителей'},
        ),
        migrations.AlterModelOptions(
            name='standmodel',
            options={'verbose_name': 'Стэнды', 'verbose_name_plural': 'Стэнды'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.CreateModel(
            name='FullPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.AboutUsModel')),
                ('cateringSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CateringModel')),
                ('registerSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RegisterModel')),
                ('standSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StandModel')),
            ],
        ),
    ]
