# Generated by Django 3.0.7 on 2020-08-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200713_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusmodel',
            options={'verbose_name': '4. О нас', 'verbose_name_plural': '4. О нас'},
        ),
        migrations.AlterModelOptions(
            name='cateringmodel',
            options={'verbose_name': '2. Кейтеринг', 'verbose_name_plural': '2. Кейтеринг'},
        ),
        migrations.AlterModelOptions(
            name='registermodel',
            options={'verbose_name': '3. Регистрация посетителей', 'verbose_name_plural': '3. Регистрация посетителей'},
        ),
        migrations.AlterModelOptions(
            name='standmodel',
            options={'verbose_name': '1. Стэнды', 'verbose_name_plural': '1. Стэнды'},
        ),
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='text',
            new_name='en_text',
        ),
        migrations.RemoveField(
            model_name='eventsmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='imagesmodel',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='othermodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='en_title',
            field=models.CharField(default='', max_length=120, verbose_name='Название(en)'),
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='ru_title',
            field=models.CharField(default='', max_length=120, verbose_name='Название(ru)'),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='en_alt',
            field=models.CharField(default='', max_length=120, verbose_name='название фотографии(en)'),
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='ru_alt',
            field=models.CharField(default='', max_length=120, verbose_name='название фотографии(ru)'),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='en_title',
            field=models.CharField(default='', max_length=120, verbose_name='Название(en)'),
        ),
        migrations.AddField(
            model_name='othermodel',
            name='ru_title',
            field=models.CharField(default='', max_length=120, verbose_name='Название(ru)'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='en_title',
            field=models.CharField(default='', max_length=120, verbose_name='название(en)'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='ru_title',
            field=models.CharField(default='', max_length=120, verbose_name='название(ru)'),
        ),
    ]
