# Generated by Django 3.0.7 on 2020-08-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200830_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='ru_text',
            field=models.TextField(default='', verbose_name='текст(ru)'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='en_text',
            field=models.TextField(default='', verbose_name='текст(en)'),
        ),
    ]
